name: Deploy Medical Tracker to Azure

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  AZURE_WEBAPP_NAME: medicaltracker
  RESOURCE_GROUP: ResourceGroup1
  GHCR_IMAGE: ghcr.io/${{ github.repository }}/medicaltracker

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    - name: Upload frontend build artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/build

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore and publish backend
      run: |
        cd backend
        dotnet restore
        dotnet publish -c Release -o ../backend-publish
    - name: Upload backend publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-publish
        path: backend-publish
    - name: Upload backend/xunit artifact
      uses: actions/upload-artifact@v4
      with:
        name: xunit-project
        path: xunit

  test:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
    - name: Download xunit artifact
      uses: actions/download-artifact@v4
      with:
        name: xunit-project
        path: xunit
    - name: Run backend xUnit tests
      run: |
        cd xunit
        dotnet test --no-build --verbosity normal

  build-docker-container:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend, test]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download frontend build artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend/build
    - name: Download backend publish artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-publish
        path: backend-publish
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT_TOKEN }}
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.GHCR_IMAGE }}:${{ github.sha }} -t ${{ env.GHCR_IMAGE }}:latest -t ${{ env.GHCR_IMAGE }}:${{ github.run_number }} .
        docker push ${{ env.GHCR_IMAGE }}:${{ github.sha }}
        docker push ${{ env.GHCR_IMAGE }}:latest
        docker push ${{ env.GHCR_IMAGE }}:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker-container
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to Azure Web App for Containers
      run: |
        az webapp config container set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ env.GHCR_IMAGE }}:${{ github.run_number }} 